
FROM node:18-alpine
WORKDIR /app

COPY backend/package.json ./
RUN npm install

COPY backend/ ./

ENV NODE_ENV=development
ENV BACKEND_PORT=3847

EXPOSE 3847

RUN chown -R node:node /app
USER node

CMD ["npm", "run", "dev"]
